---
- name: create user accounts for all our servers
  hosts: all
  remote_user: ansible
  become: true


  tasks:
    - name: test the copy module with /etc/sudoers
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /etc/sudoers.dleroux
        remote_src: yes
        validate: /usr/sbin/visudo -csf %s

    - name: copy ansible facts to a file
      ansible.builtin.copy:
        content: "{{ ansible_facts }}"
        dest: /tmp/ansible_facts_details.json
