---
- name: create user accounts for all our servers
  hosts: servers
  remote_user: ansible
  become: true


  tasks:
    - name: test the copy module
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /etc/sudoers.dleroux
        remote_src: yes
        validate: /usr/sbin/visudo -csf %s
